\set ON_ERROR_STOP on

BEGIN;

CREATE SCHEMA IF NOT EXISTS company_intelligence;

CREATE TABLE IF NOT EXISTS company_intelligence.source (
    source_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key text NOT NULL UNIQUE,
    source_name text NOT NULL,
    authority text NOT NULL,
    base_url text NOT NULL,
    officiality text NOT NULL CHECK (officiality IN ('official', 'company_official', 'secondary', 'derived')),
    redistribution_allowed boolean NOT NULL DEFAULT false,
    license_note text NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS company_intelligence.company (
    company_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edinet_code text UNIQUE,
    sec_code text UNIQUE,
    jcn text,
    legal_name_ja text NOT NULL,
    legal_name_en text,
    industry_code text,
    fiscal_year_end_month smallint CHECK (fiscal_year_end_month BETWEEN 1 AND 12),
    fiscal_year_end_day smallint CHECK (fiscal_year_end_day BETWEEN 1 AND 31),
    listed_market text,
    active boolean NOT NULL DEFAULT true,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (edinet_code IS NOT NULL OR sec_code IS NOT NULL OR jcn IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS company_intelligence.company_alias (
    company_alias_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES company_intelligence.company(company_id) ON DELETE CASCADE,
    alias text NOT NULL,
    alias_type text NOT NULL CHECK (alias_type IN ('former_name', 'brand', 'english', 'abbreviation', 'other')),
    valid_from date,
    valid_to date,
    source_id bigint REFERENCES company_intelligence.source(source_id),
    UNIQUE (company_id, alias, alias_type)
);

CREATE TABLE IF NOT EXISTS company_intelligence.ingestion_run (
    ingestion_run_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_key text NOT NULL UNIQUE,
    source_id bigint NOT NULL REFERENCES company_intelligence.source(source_id),
    started_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    status text NOT NULL CHECK (status IN ('running', 'succeeded', 'partial', 'failed')),
    scope jsonb NOT NULL DEFAULT '{}'::jsonb,
    fetched_count integer NOT NULL DEFAULT 0,
    inserted_count integer NOT NULL DEFAULT 0,
    updated_count integer NOT NULL DEFAULT 0,
    error_count integer NOT NULL DEFAULT 0,
    error_detail jsonb NOT NULL DEFAULT '[]'::jsonb,
    code_version text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS company_intelligence.raw_document (
    raw_document_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id bigint NOT NULL REFERENCES company_intelligence.source(source_id),
    company_id bigint REFERENCES company_intelligence.company(company_id),
    ingestion_run_id bigint REFERENCES company_intelligence.ingestion_run(ingestion_run_id),
    external_id text NOT NULL,
    resource_type text NOT NULL,
    canonical_url text NOT NULL,
    effective_at timestamptz,
    retrieved_at timestamptz NOT NULL DEFAULT now(),
    content_sha256 text NOT NULL,
    content_type text,
    payload jsonb,
    storage_path text,
    export_allowed boolean NOT NULL DEFAULT false,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (source_id, external_id, content_sha256)
);

CREATE TABLE IF NOT EXISTS company_intelligence.filing (
    filing_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES company_intelligence.company(company_id) ON DELETE CASCADE,
    source_id bigint NOT NULL REFERENCES company_intelligence.source(source_id),
    raw_document_id bigint REFERENCES company_intelligence.raw_document(raw_document_id),
    doc_id text NOT NULL,
    doc_type_code text,
    ordinance_code text,
    form_code text,
    filing_name text,
    submitted_at timestamptz,
    period_start date,
    period_end date,
    accounting_standard text,
    consolidated boolean,
    amendment_of_filing_id bigint REFERENCES company_intelligence.filing(filing_id),
    withdrawal_status text,
    xbrl_available boolean NOT NULL DEFAULT false,
    csv_available boolean NOT NULL DEFAULT false,
    pdf_available boolean NOT NULL DEFAULT false,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (source_id, doc_id)
);

CREATE TABLE IF NOT EXISTS company_intelligence.fact_concept (
    fact_concept_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concept_key text NOT NULL UNIQUE,
    statement_type text NOT NULL CHECK (statement_type IN ('PL', 'BS', 'CF', 'KPI', 'WORKFORCE', 'SHAREHOLDER', 'SEGMENT', 'OTHER')),
    label_ja text NOT NULL,
    label_en text,
    value_type text NOT NULL CHECK (value_type IN ('monetary', 'percentage', 'shares', 'count', 'date', 'text', 'ratio')),
    canonical_unit text,
    instant_or_duration text NOT NULL CHECK (instant_or_duration IN ('instant', 'duration', 'either')),
    aggregation_rule text NOT NULL DEFAULT 'none',
    aliases jsonb NOT NULL DEFAULT '[]'::jsonb,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS company_intelligence.fact (
    fact_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES company_intelligence.company(company_id) ON DELETE CASCADE,
    source_id bigint NOT NULL REFERENCES company_intelligence.source(source_id),
    filing_id bigint REFERENCES company_intelligence.filing(filing_id),
    raw_document_id bigint REFERENCES company_intelligence.raw_document(raw_document_id),
    fact_concept_id bigint REFERENCES company_intelligence.fact_concept(fact_concept_id),
    element_id text NOT NULL,
    label text,
    context_id text,
    period_start date,
    period_end date,
    instant_date date,
    fiscal_year integer,
    accounting_standard text,
    consolidated boolean,
    relative_fiscal_year text,
    unit_id text,
    unit_label text,
    decimals_text text,
    value_numeric numeric(38, 8),
    value_text text,
    dimensions jsonb NOT NULL DEFAULT '{}'::jsonb,
    quality_flag text NOT NULL CHECK (quality_flag IN ('official', 'company_official', 'secondary', 'derived', 'estimated', 'conflict')),
    source_priority smallint NOT NULL DEFAULT 100,
    revision integer NOT NULL DEFAULT 0 CHECK (revision >= 0),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    inserted_at timestamptz NOT NULL DEFAULT now(),
    CHECK (value_numeric IS NOT NULL OR value_text IS NOT NULL),
    UNIQUE NULLS NOT DISTINCT (
        company_id, source_id, filing_id, element_id, context_id,
        period_start, period_end, instant_date, unit_id, revision
    )
);

CREATE TABLE IF NOT EXISTS company_intelligence.fact_lineage (
    derived_fact_id bigint NOT NULL REFERENCES company_intelligence.fact(fact_id) ON DELETE CASCADE,
    input_fact_id bigint NOT NULL REFERENCES company_intelligence.fact(fact_id) ON DELETE RESTRICT,
    relation text NOT NULL CHECK (relation IN ('input', 'mapped_from', 'reconciled_against', 'calculated_from', 'supersedes')),
    weight numeric(20, 10),
    transformation jsonb NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (derived_fact_id, input_fact_id, relation)
);

CREATE TABLE IF NOT EXISTS company_intelligence.timeline_event (
    timeline_event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES company_intelligence.company(company_id) ON DELETE CASCADE,
    source_id bigint NOT NULL REFERENCES company_intelligence.source(source_id),
    raw_document_id bigint REFERENCES company_intelligence.raw_document(raw_document_id),
    event_date date,
    event_year integer,
    event_type text NOT NULL,
    title text NOT NULL,
    description text,
    significance smallint CHECK (significance BETWEEN 1 AND 5),
    source_url text,
    export_allowed boolean NOT NULL DEFAULT false,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS company_intelligence.segment_fact (
    segment_fact_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES company_intelligence.company(company_id) ON DELETE CASCADE,
    source_id bigint NOT NULL REFERENCES company_intelligence.source(source_id),
    filing_id bigint REFERENCES company_intelligence.filing(filing_id),
    raw_document_id bigint REFERENCES company_intelligence.raw_document(raw_document_id),
    fiscal_year integer NOT NULL,
    segment_name text NOT NULL,
    metric_key text NOT NULL,
    value_numeric numeric(38, 8) NOT NULL,
    unit text NOT NULL,
    dimensions jsonb NOT NULL DEFAULT '{}'::jsonb,
    quality_flag text NOT NULL,
    UNIQUE NULLS NOT DISTINCT (company_id, source_id, filing_id, fiscal_year, segment_name, metric_key, dimensions)
);

CREATE TABLE IF NOT EXISTS company_intelligence.executive_snapshot (
    executive_snapshot_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES company_intelligence.company(company_id) ON DELETE CASCADE,
    source_id bigint NOT NULL REFERENCES company_intelligence.source(source_id),
    raw_document_id bigint REFERENCES company_intelligence.raw_document(raw_document_id),
    as_of_date date NOT NULL,
    person_name text NOT NULL,
    position text NOT NULL,
    birth_date date,
    career jsonb NOT NULL DEFAULT '[]'::jsonb,
    export_allowed boolean NOT NULL DEFAULT false,
    UNIQUE (company_id, source_id, as_of_date, person_name, position)
);

CREATE TABLE IF NOT EXISTS company_intelligence.shareholder_snapshot (
    shareholder_snapshot_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES company_intelligence.company(company_id) ON DELETE CASCADE,
    source_id bigint NOT NULL REFERENCES company_intelligence.source(source_id),
    raw_document_id bigint REFERENCES company_intelligence.raw_document(raw_document_id),
    as_of_date date NOT NULL,
    holder_name text NOT NULL,
    shares numeric(38, 4),
    ownership_pct numeric(12, 6),
    rank integer,
    export_allowed boolean NOT NULL DEFAULT false,
    UNIQUE (company_id, source_id, as_of_date, holder_name)
);

CREATE TABLE IF NOT EXISTS company_intelligence.reconciliation_issue (
    reconciliation_issue_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES company_intelligence.company(company_id) ON DELETE CASCADE,
    fact_concept_id bigint REFERENCES company_intelligence.fact_concept(fact_concept_id),
    period_end date,
    official_fact_id bigint REFERENCES company_intelligence.fact(fact_id),
    comparison_fact_id bigint REFERENCES company_intelligence.fact(fact_id),
    issue_type text NOT NULL CHECK (issue_type IN ('exact_match', 'rounding_difference', 'definition_difference', 'period_difference', 'missing_official', 'missing_secondary', 'material_conflict')),
    absolute_difference numeric(38, 8),
    relative_difference numeric(20, 10),
    status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'accepted', 'resolved', 'ignored')),
    resolution_note text,
    created_at timestamptz NOT NULL DEFAULT now(),
    resolved_at timestamptz,
    UNIQUE NULLS NOT DISTINCT (company_id, fact_concept_id, period_end, official_fact_id, comparison_fact_id)
);

CREATE INDEX IF NOT EXISTS company_sec_code_idx ON company_intelligence.company(sec_code);
CREATE INDEX IF NOT EXISTS company_edinet_code_idx ON company_intelligence.company(edinet_code);
CREATE INDEX IF NOT EXISTS filing_company_period_idx ON company_intelligence.filing(company_id, period_end DESC);
CREATE INDEX IF NOT EXISTS fact_company_concept_period_idx ON company_intelligence.fact(company_id, fact_concept_id, period_end DESC, instant_date DESC);
CREATE INDEX IF NOT EXISTS fact_element_context_idx ON company_intelligence.fact(element_id, context_id);
CREATE INDEX IF NOT EXISTS fact_dimensions_gin_idx ON company_intelligence.fact USING gin(dimensions);
CREATE INDEX IF NOT EXISTS raw_document_company_type_idx ON company_intelligence.raw_document(company_id, resource_type, retrieved_at DESC);
CREATE INDEX IF NOT EXISTS timeline_company_date_idx ON company_intelligence.timeline_event(company_id, event_date DESC, event_year DESC);
CREATE INDEX IF NOT EXISTS reconciliation_open_idx ON company_intelligence.reconciliation_issue(company_id, status) WHERE status = 'open';

COMMENT ON SCHEMA company_intelligence IS
    'Auditable company-history and financial-intelligence store with EDINET-first source priority.';
COMMENT ON TABLE company_intelligence.raw_document IS
    'Immutable source snapshots. export_allowed enforces source-specific redistribution policy.';
COMMENT ON TABLE company_intelligence.fact IS
    'Raw and normalized facts. Official EDINET facts retain element/context/unit metadata.';

COMMIT;
