\set ON_ERROR_STOP on

BEGIN;

CREATE SCHEMA IF NOT EXISTS market_data;

CREATE TABLE IF NOT EXISTS market_data.source (
    source_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key text NOT NULL UNIQUE,
    source_name text NOT NULL,
    authority text NOT NULL,
    source_url text NOT NULL,
    access_method text NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS market_data.ingestion_run (
    ingestion_run_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_key text NOT NULL UNIQUE,
    started_at timestamptz NOT NULL,
    completed_at timestamptz,
    status text NOT NULL CHECK (status IN ('running', 'succeeded', 'failed')),
    code_version text,
    notes text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS market_data.series (
    series_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_key text NOT NULL UNIQUE,
    series_name text NOT NULL,
    country_code char(2),
    currency_code char(3),
    measure text NOT NULL CHECK (
        measure IN ('nominal_yield', 'real_yield', 'fx_rate', 'yield_spread')
    ),
    curve_family text,
    instrument_type text NOT NULL,
    tenor_years numeric(12, 6),
    tenor_label text,
    unit text NOT NULL,
    frequency text NOT NULL,
    quote_type text NOT NULL,
    source_id bigint NOT NULL REFERENCES market_data.source(source_id),
    methodology text NOT NULL,
    is_derived boolean NOT NULL DEFAULT false,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (tenor_years IS NULL OR tenor_years > 0)
);

CREATE TABLE IF NOT EXISTS market_data.observation (
    observation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_id bigint NOT NULL REFERENCES market_data.series(series_id) ON DELETE CASCADE,
    observed_on date NOT NULL,
    observed_at timestamptz,
    value numeric(20, 8) NOT NULL,
    revision integer NOT NULL DEFAULT 0 CHECK (revision >= 0),
    quality_flag text NOT NULL DEFAULT 'official' CHECK (
        quality_flag IN ('official', 'calculated', 'interpolated', 'proxy', 'provisional')
    ),
    source_document_url text,
    ingestion_run_id bigint REFERENCES market_data.ingestion_run(ingestion_run_id),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    inserted_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (series_id, observed_on, revision)
);

CREATE TABLE IF NOT EXISTS market_data.observation_lineage (
    derived_observation_id bigint NOT NULL REFERENCES market_data.observation(observation_id) ON DELETE CASCADE,
    input_observation_id bigint NOT NULL REFERENCES market_data.observation(observation_id) ON DELETE RESTRICT,
    relation text NOT NULL CHECK (relation IN ('input', 'interpolation_lower', 'interpolation_upper', 'proxy_input')),
    weight numeric(20, 10),
    PRIMARY KEY (derived_observation_id, input_observation_id, relation),
    CHECK (weight IS NULL OR (weight >= 0 AND weight <= 1))
);

CREATE INDEX IF NOT EXISTS observation_series_date_idx
    ON market_data.observation (series_id, observed_on DESC);
CREATE INDEX IF NOT EXISTS series_measure_tenor_idx
    ON market_data.series (measure, tenor_years);
CREATE INDEX IF NOT EXISTS series_country_curve_idx
    ON market_data.series (country_code, curve_family, tenor_years);
CREATE INDEX IF NOT EXISTS observation_metadata_gin_idx
    ON market_data.observation USING gin (metadata);

COMMENT ON SCHEMA market_data IS
    'Point-in-time market data with source provenance and derivation lineage.';
COMMENT ON TABLE market_data.observation_lineage IS
    'Links calculated, interpolated, or proxy observations to their exact input observations.';

COMMIT;
